//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambilight.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ambilight.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;layer1&quot;: {
        ///		&quot;left&quot;: {
        ///			&quot;0&quot;: {
        ///				&quot;r&quot;: 7,
        ///				&quot;g&quot;: 10,
        ///				&quot;b&quot;: 5
        ///			},
        ///			&quot;1&quot;: {
        ///				&quot;r&quot;: 40,
        ///				&quot;g&quot;: 60,
        ///				&quot;b&quot;: 33
        ///			},
        ///			&quot;2&quot;: {
        ///				&quot;r&quot;: 116,
        ///				&quot;g&quot;: 149,
        ///				&quot;b&quot;: 86
        ///			}
        ///		},
        ///		&quot;top&quot;: {
        ///			&quot;0&quot;: {
        ///				&quot;r&quot;: 109,
        ///				&quot;g&quot;: 136,
        ///				&quot;b&quot;: 76
        ///			},
        ///			&quot;1&quot;: {
        ///				&quot;r&quot;: 115,
        ///				&quot;g&quot;: 138,
        ///				&quot;b&quot;: 77
        ///			},
        ///			&quot;2&quot;: {
        ///				&quot;r&quot;: 96,
        ///				&quot;g&quot;: 115,
        ///				&quot;b&quot;: 66
        ///			},
        ///			&quot;3&quot;: {
        ///				&quot;r&quot;: 105,
        ///				&quot;g&quot;: 122,
        ///				&quot;b&quot;: 67
        ///			},
        ///			&quot;4&quot;: {
        ///				&quot;r&quot;: 90,
        ///				&quot;g&quot;: 112,
        ///				&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessedJson {
            get {
                return ResourceManager.GetString("ProcessedJson", resourceCulture);
            }
        }
    }
}
